# Generated by Django 6.0 on 2025-12-18 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyectos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=50, verbose_name="Título del proyecto"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "tecnologias",
                    models.CharField(
                        help_text="Ejemplo: Python, Django, React",
                        max_length=150,
                        verbose_name="Tecnologías usadas",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Links del proyecto"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="proyectos/",
                        verbose_name="Imagen del proyecto",
                    ),
                ),
                (
                    "videos",
                    models.URLField(blank=True, verbose_name="Video del proyecto"),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagenProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="proyectos/images/",
                        verbose_name="Imagen del proyecto",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Descripción"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="portfolio.proyectos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="proyectos/videos/",
                        verbose_name="Video del proyecto",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Descripción"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos_archivo",
                        to="portfolio.proyectos",
                    ),
                ),
            ],
        ),
    ]
