# Generated by Django 6.0 on 2025-12-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=50, verbose_name="Título del proyecto"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "tecnologias",
                    models.CharField(
                        help_text="Ejemplo: Python, Django, React",
                        max_length=150,
                        verbose_name="Tecnologías usadas",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="proyectos/certificaciones/",
                        verbose_name="Imagen del proyecto",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mycertifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=50, verbose_name="Título del proyecto"),
                ),
                (
                    "puesto",
                    models.CharField(max_length=50, verbose_name="Título del proyecto"),
                ),
                (
                    "fecha_years",
                    models.CharField(max_length=50, verbose_name="Título del proyecto"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="proyectos/logos/",
                        verbose_name="Logo de la empresa",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="proyectos/images/",
                verbose_name="Imagen del proyecto",
            ),
        ),
    ]
