# Generated by Django 6.0 on 2025-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_certifications_mycertifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycertifications",
            name="fecha_years",
            field=models.CharField(
                max_length=50, verbose_name="Fecha del proyecto ej: 2020-2025"
            ),
        ),
        migrations.AlterField(
            model_name="mycertifications",
            name="puesto",
            field=models.CharField(max_length=50, verbose_name="Puesto del proyecto"),
        ),
    ]
