# Generated by Django 6.0 on 2025-12-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_mycertifications_fecha_years_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mycertifications",
            new_name="MyWorkExperience",
        ),
    ]
