# Generated by Django 6.0 on 2025-12-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_rename_mycertifications_myworkexperience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre de la tecnología",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Link de referencia"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="proyectos/tecnologias/",
                        verbose_name="Logo de la tecnología",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tecnologias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Título del Empleo"),
                ),
                (
                    "link",
                    models.CharField(max_length=100, verbose_name="Título del Empleo"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="proyectos/certificaciones/",
                        verbose_name="Imagen del proyecto",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="certifications",
            name="tecnologias",
        ),
        migrations.AlterField(
            model_name="certifications",
            name="titulo",
            field=models.CharField(
                max_length=50, verbose_name="Título de la certificacion"
            ),
        ),
        migrations.AlterField(
            model_name="myworkexperience",
            name="puesto",
            field=models.CharField(max_length=50, verbose_name="Puesto del Empleo"),
        ),
        migrations.AlterField(
            model_name="myworkexperience",
            name="titulo",
            field=models.CharField(max_length=50, verbose_name="Título del Empleo"),
        ),
        migrations.RemoveField(
            model_name="proyectos",
            name="tecnologias",
        ),
        migrations.AddField(
            model_name="certifications",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="certifications",
                to="portfolio.technology",
                verbose_name="Tecnologías usadas",
            ),
        ),
        migrations.AddField(
            model_name="proyectos",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="proyectos",
                to="portfolio.technology",
                verbose_name="Tecnologías usadas",
            ),
        ),
    ]
