# Generated by Django 6.0 on 2025-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_technology_tecnologias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myworkexperience",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="work_experiences",
                to="portfolio.technology",
                verbose_name="Tecnologías usadas",
            ),
        ),
    ]
