# Generated by Django 6.0 on 2025-12-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_myworkexperience_tecnologias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certifications",
            name="imagen",
            field=models.URLField(
                blank=True,
                default="",
                verbose_name="URL de la imagen de la certificación",
            ),
        ),
        migrations.AlterField(
            model_name="imagenproyecto",
            name="imagen",
            field=models.URLField(verbose_name="URL de la imagen del proyecto"),
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="imagen",
            field=models.URLField(
                blank=True, verbose_name="URL de la imagen del proyecto"
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="imagen",
            field=models.URLField(
                blank=True, verbose_name="URL del logo de la tecnología"
            ),
        ),
        migrations.AlterField(
            model_name="videoproyecto",
            name="video",
            field=models.URLField(
                blank=True, verbose_name="URL del video del proyecto"
            ),
        ),
    ]
