# Generated by Django 6.0 on 2025-12-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_certifications_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyectos",
            name="repositorio",
            field=models.URLField(blank=True, verbose_name="Links del repositorio"),
        ),
        migrations.AlterField(
            model_name="certifications",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="proyectos/certificaciones/",
                verbose_name="Imagen del proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="imagenproyecto",
            name="imagen",
            field=models.ImageField(
                upload_to="proyectos/images/", verbose_name="Imagen del proyecto"
            ),
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="proyectos/images/",
                verbose_name="Imagen del proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="proyectos/tecnologias/",
                verbose_name="Logo de la tecnología",
            ),
        ),
        migrations.AlterField(
            model_name="videoproyecto",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="proyectos/videos/",
                verbose_name="Video del proyecto",
            ),
        ),
    ]
