# Generated by Django 6.0 on 2025-12-22 23:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0008_proyectos_repositorio_alter_certifications_imagen_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="certifications",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Imagen de la certificación",
            ),
        ),
        migrations.AlterField(
            model_name="imagenproyecto",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Imagen del proyecto"
            ),
        ),
        migrations.AlterField(
            model_name="myworkexperience",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Logo de la empresa"
            ),
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Imagen del proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Logo de la tecnología",
            ),
        ),
        migrations.AlterField(
            model_name="tecnologias",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Imagen del proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="videoproyecto",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Video del proyecto"
            ),
        ),
    ]
